# Generated by Django 5.1.5 on 2025-01-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_remove_sslcertificate_serial_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='sslcertificate',
            name='product_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sslcertificate',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8),
        ),
        migrations.AlterField(
            model_name='sslcertificate',
            name='created_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sslcertificate',
            name='expire_date',
            field=models.DateField(),
        ),
    ]
